/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db;


import com.test.bank.db.tables.Admin;
import com.test.bank.db.tables.Adminrole;
import com.test.bank.db.tables.Role;
import com.test.bank.db.tables.Transaction;
import com.test.bank.db.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bank</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMIN_PRIMARY = Indexes0.ADMIN_PRIMARY;
    public static final Index ADMINROLE_ADMINID = Indexes0.ADMINROLE_ADMINID;
    public static final Index ADMINROLE_PRIMARY = Indexes0.ADMINROLE_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index TRANSACTION_ADMINID = Indexes0.TRANSACTION_ADMINID;
    public static final Index TRANSACTION_FROMUSERID = Indexes0.TRANSACTION_FROMUSERID;
    public static final Index TRANSACTION_PRIMARY = Indexes0.TRANSACTION_PRIMARY;
    public static final Index TRANSACTION_TOUSERID = Indexes0.TRANSACTION_TOUSERID;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADMIN_PRIMARY = Internal.createIndex("PRIMARY", Admin.ADMIN, new OrderField[] { Admin.ADMIN.ID }, true);
        public static Index ADMINROLE_ADMINID = Internal.createIndex("adminId", Adminrole.ADMINROLE, new OrderField[] { Adminrole.ADMINROLE.ADMINID }, false);
        public static Index ADMINROLE_PRIMARY = Internal.createIndex("PRIMARY", Adminrole.ADMINROLE, new OrderField[] { Adminrole.ADMINROLE.ROLEID, Adminrole.ADMINROLE.ADMINID }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index TRANSACTION_ADMINID = Internal.createIndex("adminId", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.ADMINID }, false);
        public static Index TRANSACTION_FROMUSERID = Internal.createIndex("fromUserId", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.FROMUSERID }, false);
        public static Index TRANSACTION_PRIMARY = Internal.createIndex("PRIMARY", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.ID }, true);
        public static Index TRANSACTION_TOUSERID = Internal.createIndex("ToUserId", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.TOUSERID }, false);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
