/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db;


import com.test.bank.db.tables.Admin;
import com.test.bank.db.tables.Token;
import com.test.bank.db.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bank</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMIN_PRIMARY = Indexes0.ADMIN_PRIMARY;
    public static final Index TOKEN_PRIMARY = Indexes0.TOKEN_PRIMARY;
    public static final Index TOKEN_TOKEN = Indexes0.TOKEN_TOKEN;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADMIN_PRIMARY = Internal.createIndex("PRIMARY", Admin.ADMIN, new OrderField[] { Admin.ADMIN.ID }, true);
        public static Index TOKEN_PRIMARY = Internal.createIndex("PRIMARY", Token.TOKEN, new OrderField[] { Token.TOKEN.ADMINID }, true);
        public static Index TOKEN_TOKEN = Internal.createIndex("Token", Token.TOKEN, new OrderField[] { Token.TOKEN.TOKEN_ }, false);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
