/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db;


import com.test.bank.db.tables.Admin;
import com.test.bank.db.tables.Token;
import com.test.bank.db.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bank
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bank.Admin</code>.
     */
    public static final Admin ADMIN = com.test.bank.db.tables.Admin.ADMIN;

    /**
     * The table <code>bank.Token</code>.
     */
    public static final Token TOKEN = com.test.bank.db.tables.Token.TOKEN;

    /**
     * The table <code>bank.User</code>.
     */
    public static final User USER = com.test.bank.db.tables.User.USER;
}
