/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db;


import com.test.bank.db.tables.Admin;
import com.test.bank.db.tables.Adminrole;
import com.test.bank.db.tables.Role;
import com.test.bank.db.tables.Transaction;
import com.test.bank.db.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bank
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bank.Admin</code>.
     */
    public static final Admin ADMIN = com.test.bank.db.tables.Admin.ADMIN;

    /**
     * The table <code>bank.AdminRole</code>.
     */
    public static final Adminrole ADMINROLE = com.test.bank.db.tables.Adminrole.ADMINROLE;

    /**
     * The table <code>bank.Role</code>.
     */
    public static final Role ROLE = com.test.bank.db.tables.Role.ROLE;

    /**
     * The table <code>bank.Transaction</code>.
     */
    public static final Transaction TRANSACTION = com.test.bank.db.tables.Transaction.TRANSACTION;

    /**
     * The table <code>bank.User</code>.
     */
    public static final User USER = com.test.bank.db.tables.User.USER;
}
