/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adminrole implements Serializable {

    private static final long serialVersionUID = -953736164;

    private UInteger roleid;
    private UInteger adminid;

    public Adminrole() {}

    public Adminrole(Adminrole value) {
        this.roleid = value.roleid;
        this.adminid = value.adminid;
    }

    public Adminrole(
        UInteger roleid,
        UInteger adminid
    ) {
        this.roleid = roleid;
        this.adminid = adminid;
    }

    public UInteger getRoleid() {
        return this.roleid;
    }

    public void setRoleid(UInteger roleid) {
        this.roleid = roleid;
    }

    public UInteger getAdminid() {
        return this.adminid;
    }

    public void setAdminid(UInteger adminid) {
        this.adminid = adminid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Adminrole (");

        sb.append(roleid);
        sb.append(", ").append(adminid);

        sb.append(")");
        return sb.toString();
    }
}
