/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Token implements Serializable {

    private static final long serialVersionUID = -455068378;

    private UInteger adminid;
    private String   token;

    public Token() {}

    public Token(Token value) {
        this.adminid = value.adminid;
        this.token = value.token;
    }

    public Token(
        UInteger adminid,
        String   token
    ) {
        this.adminid = adminid;
        this.token = token;
    }

    public UInteger getAdminid() {
        return this.adminid;
    }

    public void setAdminid(UInteger adminid) {
        this.adminid = adminid;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Token (");

        sb.append(adminid);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
