/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction implements Serializable {

    private static final long serialVersionUID = 795410892;

    private UInteger  id;
    private UInteger  fromuserid;
    private UInteger  touserid;
    private Byte      action;
    private UInteger  adminid;
    private Timestamp createdat;

    public Transaction() {}

    public Transaction(Transaction value) {
        this.id = value.id;
        this.fromuserid = value.fromuserid;
        this.touserid = value.touserid;
        this.action = value.action;
        this.adminid = value.adminid;
        this.createdat = value.createdat;
    }

    public Transaction(
        UInteger  id,
        UInteger  fromuserid,
        UInteger  touserid,
        Byte      action,
        UInteger  adminid,
        Timestamp createdat
    ) {
        this.id = id;
        this.fromuserid = fromuserid;
        this.touserid = touserid;
        this.action = action;
        this.adminid = adminid;
        this.createdat = createdat;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UInteger getFromuserid() {
        return this.fromuserid;
    }

    public void setFromuserid(UInteger fromuserid) {
        this.fromuserid = fromuserid;
    }

    public UInteger getTouserid() {
        return this.touserid;
    }

    public void setTouserid(UInteger touserid) {
        this.touserid = touserid;
    }

    public Byte getAction() {
        return this.action;
    }

    public void setAction(Byte action) {
        this.action = action;
    }

    public UInteger getAdminid() {
        return this.adminid;
    }

    public void setAdminid(UInteger adminid) {
        this.adminid = adminid;
    }

    public Timestamp getCreatedat() {
        return this.createdat;
    }

    public void setCreatedat(Timestamp createdat) {
        this.createdat = createdat;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transaction (");

        sb.append(id);
        sb.append(", ").append(fromuserid);
        sb.append(", ").append(touserid);
        sb.append(", ").append(action);
        sb.append(", ").append(adminid);
        sb.append(", ").append(createdat);

        sb.append(")");
        return sb.toString();
    }
}
