/*
 * This file is generated by jOOQ.
 */
package com.test.bank.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1456227559;

    private UInteger id;
    private Integer  wallet;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.wallet = value.wallet;
    }

    public User(
        UInteger id,
        Integer  wallet
    ) {
        this.id = id;
        this.wallet = wallet;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public Integer getWallet() {
        return this.wallet;
    }

    public void setWallet(Integer wallet) {
        this.wallet = wallet;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(wallet);

        sb.append(")");
        return sb.toString();
    }
}
